import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {defineConfig, loadEnv} from 'vite';

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, '.', '');
  const buildId = new Date().toISOString().replace(/[-:.TZ]/g, '');
  return {
    plugins: [
      react(),
      tailwindcss(),
      {
        name: 'inject-build-id',
        transformIndexHtml(html) {
          return html.replace(/%BUILD_ID%/g, buildId);
        },
      },
      /* sitemap is generated by scripts/generate-sitemap.mjs (supports dynamic Supabase pages)
         and copied from public/ into dist/ during build. No plugin needed. */
    ],
    define: {
      __BUILD_ID__: JSON.stringify(buildId),
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY),
      'process.env.REMOVEBG_API_KEY': JSON.stringify(env.REMOVEBG_API_KEY),
      'process.env.EXCHANGERATE_API_KEY': JSON.stringify(env.EXCHANGERATE_API_KEY),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      port: 3000,
      strictPort: false,
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
